/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "izjbpsfasdhknyvoprod"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6amJwc2Zhc2Roa255dm9wcm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3OTk4MjcsImV4cCI6MjA3OTM3NTgyN30.atgTT9P-36y2F9u0IL9oUV9Imfrv6gHDDjHyM-hXY0E"